services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/hoteldb?sslmode=disable
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - db
      - rabbitmq
    command: ["/bin/sh", "-c", "sleep 5 && /hotel-service"]

  db:
    image: postgres:13.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hoteldb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
     image: rabbitmq:3-management
     ports:
       - "5672:5672"
       - "15672:15672"

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/hoteldb?sslmode=disable
    depends_on:
      - db
    command: ["go", "test", "./tests/unit/...", "-v", "-cover"]

volumes:
  postgres_data: