services:
  report-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - MongoDbSettings__ConnectionString=mongodb://mongodb:27017
      - MongoDbSettings__DatabaseName=ReportDB
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__QueueName=report_requests
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - report-network
      - hotel_service_hotel-network  # Updated network name

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - report-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - report-network
      - hotel_service_hotel-network  # Updated network name

volumes:
  mongodb_data:

networks:
  report-network:
    driver: bridge
  hotel_service_hotel-network:  # Updated network name
    external: true