version: '3.8'

services:
  report-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - MongoDbSettings__ConnectionString=mongodb://mongodb:27017
      - MongoDbSettings__DatabaseName=ReportDB
      - RabbitMQ__HostName=rabbitmq
      - ELASTICSEARCH_URL=http://elasticsearch:9200  # This should point to the existing Elasticsearch service
    depends_on:
      - mongodb
    networks:
      - report-network
      - hotel-network  # This should be the network where hotel-service and ELK stack are running

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - report-network

volumes:
  mongodb_data:

networks:
  report-network:
    driver: bridge
  hotel-network:
    external: true  # This assumes that the hotel-service network is already created and named 'hotel-network'