CREATE TABLE IF NOT EXISTS hotels (
    id UUID PRIMARY KEY,
    official_name VARCHAR(100) NOT NULL,
    official_surname VARCHAR(100) NOT NULL,
    company_title VARCHAR(200) NOT NULL,
    location VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);